on:
  push:
    tags:
      - '*'
      
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "Release"
        pr_reviewer: "kennyho-ml"
        pr_allow_empty: true
        
